config/routes.rb
Sprowty::Application.routes.draw do

  resources :skills, :works, :keywords, :profiles
  resource :resume, :controller => "resumes"

  resources :problems
  resources :categories
  resources :messages
  resources :profiles
  resources :feedbacks
  resources :transactions
  match '/buycoins' => 'transactions#new', :as => :buy_coins

  match '/notify' => 'notifications#notify', :as => :notifications
  #root :to  => 'notifications#notify'

  resources :projects do
    get :inside
    get :approve
    get :cancel
    collection do
      get :dashboard
    end
    resources :problems
    resources :bids do
      get :accept
      get :reject
    end
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match '/approve_work/:id' => 'works#approve', :as => 'approve_work'
  match '/approve_profile/:id' => 'profiles#approve', :as => 'approve_profile'

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'login',  :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :projects, :users
  end

  match '/search'                 => 'search#index', :as => 'search'
  root :to                        => 'home#index'
  match 'inbox'                   => 'messages#index',  :as => 'inbox'
  match '/user'                   => 'profiles#index',  :as => :user_root # why are we doing this? rr
  match "/community"              => 'community#index'
  match '/community_project/:id'  => 'community#show', :as => :community_project
  match '/community_overview'     => 'community#overview', :as => :community_overview
  match '/contact'                => 'home#contact'
  match '/terms'                  => 'home#terms'
  match '/how_to'                 => 'home#how_to'
  match '/faq'                    => 'home#faq'
  match '/blog'                   => 'home#blog'
end

app/views/admin/index.html.haml
#container
  #main
    .content
      .head
        .left
          %h5 Approve Projects
        .right
          %ul.big
      #inboxhead
        %b.left Order #
        %b.right Action
        .clear
      #inbox
        .post{:style=>'border-bottom: 1px solid #D6BF9E;'}
          - @projects.each do |project|
            .row
              .field{:style=>'min-width:10%;'}
                = link_to project.id, '#'
              .field{:style=>'min-width:20%;'}
                = project.title
              .field{:style=>'min-width:10%;'}
                = project.updated_at.strftime("%b %d, %Y")
              .field{:style=>'min-width:10%;'}
                = link_to 'approve', project_approve_url(project)
            .clear
      .pagination{:style => 'float: left; margin-top: 20px; margin-left: 300px;'}
        = will_paginate @projects
  .clear

app/views/admin/show.html.haml
= render :partial => 'plant'
#container
  #main
    .rightside
      %h2 Harvest Fields
      %p Find the jobs you want to do
      %form#search{:action => "", :method => "get", :name => "input"}
        %input{:name => "Search", :onblur => "if(this.value=='')this.value='Search'", :onfocus => "if(this.value=='Search')this.value=''", :type => "text", :value => "Search"}/
        %button{:type => "submit"} Search
      .clear
      = render :partial => 'shared/categories'
    .content
      .convohead
        .left
          %h5 Project Description
      #listings
        .posttwo{:style=>'background: inherit;'}
          .sprowts
            %b
              = @project.bids.length
            %p Sprowts
            %p (Bids)
          .pic
            = link_to image_tag(@project.user.profile.picture.url(:thumb)), profile_path(@project.user)
          .info
            %h2= @project.title
            %ul.posted
              %li
                %b Due:
                = @project.due_date.strftime("%m/%d/%Y")
              %li
                %b By:
                %a#stay-target-1.stay-tooltip-target.tooltip-target= link_to @project.user.profile.full_name, profile_path(@project.user)

            %ul.posted
              %li{:style => 'float: left;'}
                %b In Category:
                = link_to @project.category, root_url(:category => @project.category)
                .clear

              %li.sprowtit{:style => 'float: right;margin-right: -110px;'}
                = link_to(image_tag('button_sprowtit.png'), new_project_bid_path(:project_id => @project.id))
                .clear

              %li{:style => 'float: left; margin-top: 20px;'}
                - unless @project.city.blank? || @project.state.blank?
                  %b Location:
                  = link_to "#{@project.city}, #{@project.state}", '#'
                .clear
            .clear
            #description
            %p= @project.description
            %ul.actions
              %li
                = link_to "Create Similar", new_project_url(:source_id => @project.id)
              %li.share
                = display_sharing_tooltip
            #stay-content-2.stay-tooltip-username.tooltip-share
              %ul
                %li
                  %a.facebook{:href => "#"}
                %li
                  %a.twitter{:href => "#"}
                %li
                  %a.email{:href => "#"}
          .price
            %h4= number_to_currency(@project.price, :precision => 0)
            %i Asking Price
          .clear
  .clear