config/routes.rb
Sprowty::Application.routes.draw do

  resources :skills, :works, :keywords, :profiles
  resource :resume, :controller => "resumes"

  resources :problems
  resources :categories
  resources :messages
  resources :profiles
  resources :feedbacks
  resources :transactions
  match '/buycoins' => 'transactions#new', :as => :buy_coins

  match '/notify' => 'notifications#notify', :as => :notifications
  #root :to  => 'notifications#notify'

  resources :projects do
    get :inside
    get :approve
    get :cancel
    collection do
      get :dashboard
    end
    resources :problems
    resources :bids do
      get :accept
      get :reject
    end
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match '/approve_work/:id' => 'works#approve', :as => 'approve_work'
  match '/approve_profile/:id' => 'profiles#approve', :as => 'approve_profile'

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'login',  :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :projects, :users
  end

  match '/search'                 => 'search#index', :as => 'search'
  root :to                        => 'home#index'
  match 'inbox'                   => 'messages#index',  :as => 'inbox'
  match '/user'                   => 'profiles#index',  :as => :user_root # why are we doing this? rr
  match "/community"              => 'community#index'
  match '/community_project/:id'  => 'community#show', :as => :community_project
  match '/community_overview'     => 'community#overview', :as => :community_overview
  match '/contact'                => 'home#contact'
  match '/terms'                  => 'home#terms'
  match '/how_to'                 => 'home#how_to'
  match '/faq'                    => 'home#faq'
  match '/blog'                   => 'home#blog'
end

app/views/shared/_categories.haml
.boxhead
  %h3 Categories
.box
  %ul.categories
    - Category.all.each do |category|
      %li
        = link_to category.name, root_url(:category => category.name)
        .clear
      %li.spacer
        .clear

app/views/shared/_feedback.haml
%h2 Feedback:
.clear
- unless @feedbacks.blank?
  - @feedbacks.last(3).each do |feedback|
    .holder
      .up
      .left
        %h6
          = Project.find(feedback.project_id).title
        %b.post
          By:
          = link_to Project.find(feedback.project_id).user.username, profile_url(Project.find(feedback.project_id).user)
        .clear
        %p
          = feedback.feedback
    .clear
    = link_to 'see all feedback', '#'
    %hr{:style => 'color: #d6bf9e;'}
- else
  %h6
    Sorry, no feedback has been reported for this user.
.clear

app/views/shared/_search.haml
= form_for :search, :url => search_url do |f|
  = f.text_field :title_or_description_or_zipcode_contains, :placeholder => 'Search'
  = hidden_field_tag "source", "search"
  %button{:type => "submit"} Search
.clear

app/views/shared/_sign_up.html.haml
#signupcontainer
  - @user.build_profile
  = form_for(@user, :url => registration_path('user')) do |f|
    .left
      = f.fields_for :profile do |p|
        .profile_fields
          = p.text_field :first_name, :class => 'field clearField', :placeholder => 'enter first name'
          = p.text_field :last_name, :class => 'field clearField', :placeholder => 'enter last name'
          = p.text_field :zipcode, :class => 'fieldlast clearField', :placeholder => 'enter zipcode'

      .user_fields
        = f.email_field :email,                     :class => 'field clearField', :placeholder => 'enter email'
        = f.password_field :password,               :class => 'field clearField', :placeholder => 'enter password'
        = f.password_field :password_confirmation,  :class => 'field clearField', :placeholder => 'confirm password'

    / LEFT
    .right
      .member{:style => "padding-left:35px; padding-top:45px"}
        Already have an account?
        %a{:href => user_session_path} Sign In
      %br/
      %br/
      = link_to image_tag('fbconnect.png', :class => 'fbconnect'), user_omniauth_authorize_path(:facebook)
      %br/
      %br/
      %div{:style => "padding-left:22px; padding-bottom:2px; margin-left: 55px;"}
        = f.check_box :terms, :class => 'checkbox', :style => 'width: auto'
        I agree to the
        %a{:href => "/terms"}
          Terms of Service
          %br/
          %br/
      = f.submit 'Join', :class => 'join'
.clear