config/routes.rb
Sprowty::Application.routes.draw do

  resources :skills, :works, :keywords, :profiles
  resource :resume, :controller => "resumes"

  resources :problems
  resources :categories
  resources :messages
  resources :profiles
  resources :feedbacks
  resources :transactions
  match '/buycoins' => 'transactions#new', :as => :buy_coins

  match '/notify' => 'notifications#notify', :as => :notifications
  #root :to  => 'notifications#notify'

  resources :projects do
    get :inside
    get :approve
    get :cancel
    collection do
      get :dashboard
    end
    resources :problems
    resources :bids do
      get :accept
      get :reject
    end
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match '/approve_work/:id' => 'works#approve', :as => 'approve_work'
  match '/approve_profile/:id' => 'profiles#approve', :as => 'approve_profile'

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'login',  :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :projects, :users
  end

  match '/search'                 => 'search#index', :as => 'search'
  root :to                        => 'home#index'
  match 'inbox'                   => 'messages#index',  :as => 'inbox'
  match '/user'                   => 'profiles#index',  :as => :user_root # why are we doing this? rr
  match "/community"              => 'community#index'
  match '/community_project/:id'  => 'community#show', :as => :community_project
  match '/community_overview'     => 'community#overview', :as => :community_overview
  match '/contact'                => 'home#contact'
  match '/terms'                  => 'home#terms'
  match '/how_to'                 => 'home#how_to'
  match '/faq'                    => 'home#faq'
  match '/blog'                   => 'home#blog'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    @search   = Project.where("sm_state != 'pending_post'").search(params[:search])

    if params[:city] && params[:state]
      @search = Project.where("sm_state != 'pending_post'", :city => params[:city], :state => params[:state]).search(params[:search])
    end

    if params[:category] && !params[:category].blank?
      @search = Project.where("sm_state != 'pending_post'", :category => params[:category]).search(params[:search])
    end

    @projects = @search.paginate(:page => params[:page], :per_page => 5, :order => 'created_at desc')
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def display_sharing_tooltip
    link_to 'Share', '#',
      :id => 'stay-target-12',
      :class => 'stay-tooltip-target.tooltip-target tiptip',
      :title => "<ul class='share_icons'>" +
                "<li>#{link_to(image_tag('icon_facebook.png'),'#')}</li>" +
                "<li>#{link_to(image_tag('icon_twitter.png'), '#')}</li>" +
                "<li>#{link_to(image_tag('icon_mail.png'), '#')}</li>" +
                "</ul>"
  end

  def display_poster_tooltip(project)
    link_to project.user.full_name || 'Author', project.user.profile,
      :id => 'poster_tip',
      :class => 'stay-tooltip-target.tooltip-target tiptip',
      :title => "<ul class='poster_tip'>" +
                "<li class='username'>#{link_to project.user.username}</li>" +
                "<li class='location'>City, State</li>" +
                "<ul class='ratings'>" +
                "<li class='positive'>0</li>" +
                "<li class='negative'>0</li>" +
                "</ul></ul>"
  end

end

app/views/home/_categories.html.haml
.boxhead{:style => 'margin-top: 50px'}
  %h3 Categories
.box
  %ul.categories
    %li
      %a{:href => "#"} Sample Link
    %li
      %a{:href => "#"} Sample Link
    %li
      %a{:href => "#"} Sample Link
    %li
      %a{:href => "#"} Sample Link
/ /BOX

app/views/home/_twitter.html.haml
= image_tag 'icon_rooster.png', :class => 'rooster'
.twitbox
  #twitter
    %ul#twitter_update_list
      %li
  %span.quote
/ /TWITBOX
.follow
  %h2
    %a{:href => "http://twitter.com/#!/sprowty", :target => "_blank"} @sprowty

app/views/home/contact.html.haml
= render :partial => 'projects/plant'
#container
  #main
    .content
      .head
        .left{:style => 'width: 300px;'}
          %h5 Contact Us
      .contactus{:style => 'margin: 10px;'}
        %form{:name => "email", :id => "email", :action => "/contact", :method => "post", :enctype => "text/plain"}
          .settings
            .label
              %label Full Namr:
            .input
              = text_field :full_name, :class => 'field'
            .label
              %label Email:
            .input
              = text_field :email, :class => 'field'
          / /SETTINGS
          .clear
          .settings
            .label
              %label Order Number:
            .input
              = text_field :order_number, :class => 'field'
          .clear
          .settings
            .label
              %label Subject:
            .input
              = select :subject, CATEGORIES, {:include_blank => false}
          .clear
          .settings
            .label
              %label message
            .input
              = text_area :message, :class => 'field'
            .clear
          = submit_tag "send", :class => 'send_btn'
    .rightside
      %h2 Sprowt Around
      %p Find the jobs you want to do
      = form_for :search, :url => search_url do |f|
        = f.text_field :title_or_description_contains, :placeholder => 'Search'
        = hidden_field_tag "source", "search"
        %button{:type => "submit"} Search
      .clear
      %br/

      = render :partial => 'shared/categories'

      #inbox
  .clear

app/views/home/faq.html.haml
= render :partial => 'projects/plant'
#container
  #main
    .content
      .head
        .left{:style => 'width: 300px;'}
          %h5 Frequently Asked Questions
        .clear
      .faq
        .section
          %h4
            General Questions:

          %h4
            What does Sprowty do?

          Sprowty is the quick and easy way to get your projects done online. It is a social marketplace created for two types of individuals. People who need random projects done, and people who are willing to do those random projects for pay.

          %h4
            How do I become a member?

          Becoming a Sprowty member is free and easy. Simply go to Sprowty.com, (it’s with a “w”) and on the top right hand corner there is a “sign up” button. Click that and you will be directed to a sign up page where you can submit your desired username, your email address, and password. Once all of that has been submitted, simply click the “create” button. After that you’ll receive an email to confirm your membership. Follow those instructions and after that you are an offical Sprowty member.

        .section
          %h4
            I’m a Seeder (I need something done)

          %h4
            What is planting a seed?

          Planting a seed is Sprowty lingo for sumbiting a task that you need done.

          %h4
            How do I plant a Seed?

          Planting a seed is free and simple:

          On the top of the Sprowty homescreen there is a green banner with text saying “Need Something Done?” To the right of the text, there is a space where you can write what you need done, by simply clicking on the text space. After you write your project title in the space, you then click the “Plant” button on the right. Upon clicking, a pop-up will appear, asking for the Job title, description, tags, and what category should it belong to. It also asks for the project’s due date and price that you are willing to pay. After that, you click the “Plant Seed” button on the bottom of the pop-up and your project has been entered for reviewal. Once it has been approved it will appear for all Sprowty members to see and bid on. If approved, your project will appear in your projects tab, which can be found on the top of any page, including the home page. There you can view and edit your project. You can only edit your project until you receive your first bid.

          %h4
            How do I know if my project has been approved?

          As soon as Sprowty decides whether your project has been approved or denied, you will receive an email with said decision.

          %h4
            How do I edit an approved project?

          If approved, your project will appear in your projects tab, which can be found on the top of any page, including the home page. There you can view and edit your project. You can only edit your project until you receive your first bid.

          %h4
            How will people find my project?

          As soon as Sprowty approves your project, it will appear on the Sprowty homepage along with all the other newest projects. To improve your chances of being found, add keywords to your post so that it can be found more easily in a search.


          %h4
            How do I know if someone placed a bid on my project?

          Whenever any Sprowty member bids to work on your project you will receive an email notification saying so. There will also be an alert above the projects tab, which can be found on the top of any page, including the home page. In the projects page, you will see all the projects, which you have posted and worked on. Find the project that you’re wondering about, and click on it. You will then see all the current bids on your project.

          %h4
            How do I select someone to work on my project?

            To view all the bids on your project, you must go into your projects tab, can be found on the top of any page, including the home page. In the projects page, you will see all the projects, which you have posted and worked on. Find the project that you’re wondering about, and click on it. You will then see all the current bids on your project. There you will see if someone has placed a bid to work on your project. You can then accept, decline, or place a counter-offer.

          %h4
            How do I cancel a project I’ve posted?

          You can only cancel a project before you have accepted a Sprowty member to work on it. If you would like to remove a posted project go to yhe projects tab, which can be found on the top of every page, including the home page. In projects you will see the option to edit or cancel your project.

          %h4
            How do I know that whomever I choose will do good work?

          Before all else, it is very important to provide a thorough and complete description of the job. After that make sure to keep in constant contact with the provider, using the Sprowty inbox system. To make sure you choose the best possible provider, every Sprowty member is encouraged to upload a resume and a portfolio of previous work they’ve done. You can access a bidders resume and or portfolio by going to their profile. You can access any Sprowty member’s profile by clicking on the user’s name. On the profile you have access to the user’s resume, portfolio, and user rating.

          %h4
            How do I know the status of my order?

          The status of your project can be found in your projects tab, which is located on the top of every page, including the home page. If you have multiple projects, click the one you’d like to know the status of. Upon clicking, you will see the status of your project, which will be either job successfully posted, waiting for bids, work in progress, or work is completed. Be sure that once the work is completed to leave the appropriate feedback.


          %h4
            How do I know when my project is complete?

          The status of your project can be found in your projects tab, which is located on the top of every page, including the home page. If you have multiple projects, click the one you’d like to know the status of. Upon clicking, you will see the status of your project, which will be either job successfully posted, waiting for bids, work in progress, or work is completed. Be sure that once the work is completed to leave the appropriate feedback.


          %h4
            What do I do if I’m unsatisfied with my final product?

          If you’re unsatisfied with the final product, let the Sprowter know what was done incorrectly, so that the issue can be resolved. If however, you are not able to come to an agreement with the Sprowter, or if you cannot reach him or her, you can report a problem by going to your projects page. To access your projects page go to the top of any page, including the home page.


        .section
          %h4
            I am a Sprowter (I want to work)

          %h4
            What is Sprowting a seed, or Sprowt it?

          Sprowting a seed or Sprowt it is Sprowty lingo for working on a posted project. If you’d like to work on a posted project, simply click the Sprowt it key beside the project description and follow the instructions on the subsequent pages. After this, you do not automatically become the project’s Sprowter. The Seeder, the one that posted the project, will need to select you from among the other bidders that are interested in working on that project.

          %h4
            How do I find work on Sprowty?

          Easily. Simply use the search tab above the categories to do a specific keyword-based search on posted jobs. For a more general search, use the categories and find jobs within certain fields.

          %h4
            How do I improve my chances of getting selected?

          There are plenty of legitimate ways to let a Seeder know that you are supremrely qualified to take on the project. Your first chance to impress is when you’re filling in the “why should I be selected” text box. More importantly though, is uploading your resume and portfolio so Seeders can get a good idea of how qualified you are. Last but not least, work hard so that your feedback is positive.

          %h4
            I placed a bid to work on a project, now what?

          Your future is a three-pronged fork.
          %ol{:style => 'margin-left: 30px;margin-top: 5px;'}
            %li
              Your Bid is accepted- if this happens you will be notified via email, and you will be able to   begin communicating with the Seeder on the Sprowty messaging system.
            %li
              Your Bid is rejected- this is the end of your road on this given project. You will be notified of the rejection via email. But worry not, there are plenty of seeds in the sea.
            %li
              Counter-offer- this means that the Seeder is interested in working with you, but believes your offer price is too high. You can either…

          %h4
            How do I submit completed work?

          To submit completed work—mo don’t know how

          %h4
            When do I get paid?

          Once your submitted work is approved by the Seeder, funds will be transferred from Sprowty escrow to your personal Sprowty account, where it can be withdrawn. To withdraw your funds go to your profile page.

          %h4
            What if my work is not approved?

          If the Seeder for any reason finds your work unsatisfactory, he or she must provide a reason for such. You will then have the opportunity to amend any of the indicated issues, and resubmit the work. If you believe that the rejected was unwarranted, you can report a problem to the Sprowty team and we will review your case.

          %h4
            How long does it take for the funds to reach my personal bank account?

          NEED INFO

        .section
          %h4
            Contact Help Desk
          If none of the FAQS work for you please email us at askus@sprowty.com

    .rightside
      %h2 Sprowt Around
      %p Find the jobs you want to do
      = form_for :search, :url => search_url do |f|
        = f.text_field :title_or_description_contains, :placeholder => 'Search'
        = hidden_field_tag "source", "search"
        %button{:type => "submit"} Search
      .clear
      %br/

      = render :partial => 'shared/categories'

      #inbox
  .clear

app/views/home/how_to.html.haml
#container
  #main
    %h2 This is the how to page
    

app/views/home/index.html.haml
- unless current_user
  #slider
    .slide
      .holder
        = image_tag 'seeder-button-on.png'
        = link_to image_tag('sprowter-button-off.png'), '', :class => 'next-slide'
        %br/
        .slider
          %ul
            %li
              = image_tag 'plant-seed.png', :style => 'margin-top: 10px; padding-bottom: 10px;'
              %p{:style => 'color: #edefae;'}<
                Post what you need done.
            %li
              = image_tag 'get-sprowter.png'
              %p{:style => 'color: #edefae;'}<
                Wait for bids, and choose who you like best.
            %li
              = image_tag 'watch-sprowt.png', :style => 'margin-top: 10px;'
              %p{:style => 'color: #edefae;'}<
                Watch your project progress.
            %li
              = image_tag 'grown-up.png', :style => 'margin-top: 10px;'
              %p{:style => 'color: #edefae;'}<
                Your project is complete, leave feedback and relax!
      .seeder-image
        = image_tag 'seeder-slider.png'
    .slide{:style => 'display: none;'}
      .holder
        = link_to image_tag('seeder-button-off.png'), '', :class => 'previous-slide'
        = image_tag 'sprowter-button-on.png'
        %br/
        .slider
          %ul
            %li
              = image_tag 'set-skills.png', :style => 'margin-top: 10px;'
              %p{:style => 'color: #edefae;'}<
                List what you’re good at, and the jobs will come to you.
            %li
              = image_tag 'sprowt-around.png', :style => 'margin-top: 10px;'
              %p{:style => 'color: #edefae;'}<
                Search for jobs you’re interested in.
            %li
              = image_tag 'start-bidding.png', :style => 'margin-top: 10px;'
              %p{:style => 'color: #edefae;'}<
                Use tokens to bid on any open job.
            %li
              = image_tag 'rake-money.png', :style => 'margin-top: 10px;'
              %p{:style => 'color: #edefae;'}<
                Self-explanatory, we hope!


      .sprowter-image
        = image_tag 'sprowter-slider.png'
    .clear
  / /SLIDER
- else
  #subhead
.holder
#needdone
  .holder
    .left
      %h4 Need Something Done?
    / /LEFT
    .right
      = form_tag('/projects/new', :method => :get, :id => 'search') do
        = text_field_tag "title", nil, :class => 'field', :placeholder => "Type What You Need Done Here"
        %button{:type => "submit"} Plant
    / /RIGHT
/ /NEEDDONE
#container
  #main
    .rightside
      %h2 Sprowt Around
      %p Find the jobs you want to do
      = render :partial => 'shared/search'
      %br/
      = render :partial => 'shared/categories'
      / /BOX
    / /RIGHTSIDE
    .content{:style => 'float: none;'}
      - [:notice, :error].each do |key|
        - unless flash[key].blank?
          %div{:id => "flash_#{key}" }
            .msg
              = flash[key]
            .clear
      .head{:style=>'width: 634px;'}
        .left{:style=>'padding-top: 11px;'}
          %h2 All Jobs
        / /LEFT
        .right{:style=>'width: 425px;'}
          %ul
            %li.sort
              %b Filter By:
            %li= sort_link @search, :created_at, 'Newest'
            %li= sort_link @search, :due_date, 'Expiration'
            %li= sort_link @search, :price
            %li= sort_link @search, :bid_count, 'Sprowt count'
        / /RIGHT
      / /HEAD
      #listings{:style => 'float: left;'}
        - @projects.each do |project|
          .post
            .sprowts
              %span.bold.bid_count= project.bids.length
              %p Sprowts
              %p (Bids)
            .pic= link_to image_tag(project.user.profile.picture.url, :size => "129x129"), profile_path(project.user)
            .info
              %h2= link_to project.title, project_path(project.id)
              %ul.posted
                %li
                  %b Due:
                  = project.due_date.strftime("%m/%d/%Y")
                %li
                  %b By:
                  = link_to project.user.profile.full_name, project.user.profile

              %ul.posted
                %li
                  - if !project.city.blank? || !project.state.blank?
                    %b Location:
                    = link_to "#{project.city}, #{project.state}", root_url(:city => project.city, :state => project.state)
              / /Posted
              #description
                .keywords
                  = #link_to project.category, root_url(:category=>project.category), :style => "color: #894125;  font-family: Georgia,'Times New Roman',Serif; font-size: 14px;"
              %p
                = project.description.truncate(60)
                = link_to 'Read More', project, :class => 'readmore'
              %ul.actions
                %li= link_to 'Sprowt it', new_project_bid_path(:project_id => project.id), :class => (current_user ? 'sprowt' : '')
                %li= link_to "Create Similar", new_project_url(:source_id => project.id)

                %li.share
                  = display_sharing_tooltip
              / /stay-content-12
            / /INFO
            .price
              %h4= number_to_currency(project.price, :precision => 0)
              %i Asking Price
            .clear
              / /POST TWO
        .pagination{:style => 'float: left; margin-top: 20px; margin-left: 300px;'}
          = will_paginate @projects
      / /LISTINGS
    / /CONTENT
  .clear
  / /MAIN

/ /CONTAINER

%script{:charset => "utf-8", :type => "text/javascript"}
  jQuery(function() {
  jQuery('#plant_it').bind('click', function(e) {
  e.preventDefault();
  var link = "#{new_project_url}";
  link = link + '?title=' + jQuery('#what_you_need_done').val();
  jQuery.colorbox({ href: link, width: "800px", Height: "640px" });
  });
  });

app/views/home/terms.html.haml
= render :partial => 'projects/plant'
#container
  #main
    .content
      .head
        .left{:style => 'width: 300px;'}
          %h5 Terms of Service
        .clear

    .rightside
      %h2 Sprowt Around
      %p Find the jobs you want to do
      = form_for :search, :url => search_url do |f|
        = f.text_field :title_or_description_contains, :placeholder => 'Search'
        = hidden_field_tag "source", "search"
        %button{:type => "submit"} Search
      .clear
      %br/

      = render :partial => 'shared/categories'

      #inbox
  .clear