config/routes.rb
Sprowty::Application.routes.draw do

  resources :skills, :works, :keywords, :profiles
  resource :resume, :controller => "resumes"

  resources :problems
  resources :categories
  resources :messages
  resources :profiles
  resources :feedbacks
  resources :transactions
  match '/buycoins' => 'transactions#new', :as => :buy_coins

  match '/notify' => 'notifications#notify', :as => :notifications
  #root :to  => 'notifications#notify'

  resources :projects do
    get :inside
    get :approve
    get :cancel
    collection do
      get :dashboard
    end
    resources :problems
    resources :bids do
      get :accept
      get :reject
    end
  end

  match '/admin' => 'admin#index', :as => 'admin'

  match '/approve_work/:id' => 'works#approve', :as => 'approve_work'
  match '/approve_profile/:id' => 'profiles#approve', :as => 'approve_profile'

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'login',  :to => 'devise/sessions#new'
    get 'logout', :to => 'devise/sessions#destroy'
  end

  namespace :admin do
    resources :projects, :users
  end

  match '/search'                 => 'search#index', :as => 'search'
  root :to                        => 'home#index'
  match 'inbox'                   => 'messages#index',  :as => 'inbox'
  match '/user'                   => 'profiles#index',  :as => :user_root # why are we doing this? rr
  match "/community"              => 'community#index'
  match '/community_project/:id'  => 'community#show', :as => :community_project
  match '/community_overview'     => 'community#overview', :as => :community_overview
  match '/contact'                => 'home#contact'
  match '/terms'                  => 'home#terms'
  match '/how_to'                 => 'home#how_to'
  match '/faq'                    => 'home#faq'
  match '/blog'                   => 'home#blog'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :bids
  has_many :project_alerts
  has_many :problems
  has_many :categories

  validates_presence_of :title, :description, :category, :price, :due_date
  validate :price_increments
  validate :price_minimum

  state_machine :sm_state, :initial => :pending_post do
    event :post do transition :pending_post => :posted end
    event :waiting_for_bids do transition :posted => :waiting_for_bids end
    event :post_bid do transition :waiting_for_bids => :bid_received end
    event :accept_bid do transition :bid_received => :assigned end
    event :reject_bid do transition :bid_received => :waiting_for_bids end
    event :submit_payment do transition :assigned => :funded end
    event :work_started do transition :funded => :work_in_progress end
    event :work_completed do transition :work_in_progress => :work_completed end
    event :post_issue do transition :work_completed => :work_in_progress end
  end

  def price_increments
    unless price % 5 == 0
      errors.add(:price, 'must be in increments of $5')
    end
  end

  def price_minimum
    unless price > 0
      errors.add(:price, 'must be a minimum of $5')
    end
  end
end

app/controllers/admin/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  respond_to :html, :js

  def index
   @projects = current_user.projects

   if params[:filter]
     @filter = params[:filter]
     case @filter
       when @filter == 'open' then @projects.where(:state => 'open')
       when @filter == 'completed' then @projects.where(:state => 'completed')
     end
   end

   @tags = @projects.map(&:tags).uniq
  end

  def new
    @project        = Project.new
    if params[:source_id] && !params[:source_id].blank?
      @source = Project.find(params[:source_id])
      @project.title = @source.title
      @project.description = @source.description
      @project.category = @source.category
    end
    if params[:title] && !params[:title].blank?
      @project.title  = params[:title]
    end
    @categories = Category.all
  end

  def create
    if params[:project][:price].scan("$").length > 0
      params[:project][:price].delete!('$')
    end
    @project = current_user.projects.build(params[:project])
    if @project.save!
      respond_to do |format|
        format.html {redirect_to @project}
      end
    else
      respond_to do |format|
        render :action => 'new'
      end
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def inside
    @project = Project.find(params[:project_id])
    @project_alerts = @project.project_alerts.paginate(:page => params[:page], :per_page => 5, :order => 'created_at ASC')
  end

  def approve
    @project = Project.find(params[:project_id])
    @project.post
    redirect_to :back
  end

  def cancel
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  respond_to :html, :js

  def index
   @projects = current_user.projects.paginate(:page => params[:page], :per_page => 10)

   if params[:filter]
     @filter = params[:filter]
     case @filter
       when @filter == 'open' then @projects.where(:state => 'open')
       when @filter == 'completed' then @projects.where(:state => 'completed')
     end
   end

   @tags = @projects.map(&:tags).uniq
  end

  def new
    @project        = Project.new
    if params[:source_id] && !params[:source_id].blank?
      @source = Project.find(params[:source_id])
      @project.title = @source.title
      @project.description = @source.description
      @project.category = @source.category
    end

    if params[:title] && !params[:title].blank?
      @project.title  = params[:title]
    end

    @categories = Category.all
  end

  def create
    if params[:project][:price].scan("$").length > 0
      params[:project][:price].delete!('$')
    end

    @project = current_user.projects.build(params[:project])

    unless params[:project][:zipcode].blank?
      if zipcode = ZipCode.where(:zipcode => params[:project][:zipcode]).first
        @city = params[:project][:city] = zipcode.city
        @state = params[:project][:state] = zipcode.state
        @project.city = @city.humanize
        @project.state = @state
      end
    end

    if @project.save!
      respond_to do |format|
        format.html {redirect_to @project}
      end
    else
      respond_to do |format|
        render :action => 'new'
      end
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def inside
    @project = Project.find(params[:project_id])
    @project_alerts = @project.project_alerts.paginate(:page => params[:page], :per_page => 5, :order => 'created_at ASC')
  end

  def approve
    @project = Project.find(params[:project_id])
    @project.post
    redirect_to :back
  end

  def cancel
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.haml
= form_for(@project) do |f|
  - unless error_messages_for.nil?
    %p= error_messages_for :project
  .left
    .labelholder
      %label Job Title:
    = f.text_field :title, :class => 'field'
    .labelholder
      %label Category:
      %i Choose the category your job should be listed in
    = f.select :category, CATEGORIES, {:include_blank => true}
    .clear
    %br/
    .labelholder
      %label Description:
      %i Insert the full description and guidelines of your job
    = f.text_area :description, :class => 'field'
    .labelholder
      %label Zip Code:
      %i Optional zip code
    = f.text_field :zipcode, :class => 'field'
    .labelholder
      %label Due Date:
      %i Select Your Due Date
    = f.date_select :due_date, { :order => [:month, :day, :year], :use_month_numbers => false }, :class => 'date'
    .clear
    .labelholder
      %label Price:
      %i Enter in Increments of $5
    = f.text_field :price, :value => '$5', :onfocus => "if(this.value=='$5')this.value=''", :onblur => "if(this.value=='')this.value='$5'", :class => 'price'
    .clear
  .clear
  = f.submit 'Plant Seed', :class => 'plantseed'
  .clear
  %br/

app/views/admin/projects/_messages.haml
- project.project_alerts.each do |message|
  #listings
    - unless message.alert_type == "bid"
      .post
        .field
          = link_to image_tag(project.user.profile.picture.url(:thumb)), profile_path(project.user)
        .field
          = project.user.username
          %br/
        .field
          = project.title
          = message.message
        .field
          = message_icon_for(message.message)
          %div
            = message.occurred.strftime("%b %d, %Y - %H:%M")
      .clear
    - else
      .post
        .field
          Choose Sprowter
          %br
          (Accept Provider)
        .field
          = link_to 'Cancel Project', project_cancel_path(project.id)
        %ul.sprowter
          %li.left
            = link_to image_tag(Bid.find(message.bid_id).user.profile.picture.url(:thumb), :size => '60x60'), profile_path(Bid.find(message.bid_id).user)
          %li.left
            = link_to Bid.find(message.bid_id).user.username, profile_path(Bid.find(message.bid_id).user)

          %li.left
            = link_to 'Feedback',  feedbacks_url(:user_id => Bid.find(message.bid_id).user.id)
          %li.left

          %li.left{:style=>'background:none;'}
            = link_to 'Feedback',  profile_url(Bid.find(message.bid_id).user.id)
          %li.left{:style=>'background:none;'}

            = link_to 'Resume', '#'

        %p.text
          = message.message
        .field
          = message_icon_for(message.message)
        %ul.sprowter
          %li.left
            = link_to "Accept", project_bid_accept_path(project.id, message.bid_id)
          %li.left
            = link_to "Decline", project_bid_reject_path(project.id, message.bid_id)
          %li.left
            = link_to "Counter Offer", new_project_bid_path(:project_id => project.id, :coffer => true)

app/views/admin/projects/_plant.haml
#subhead
#needdone
  .holder
    .left
      %h4 Need Something Done?
    .right
      = form_tag('/projects/new', :method => :get, :id => 'search') do
        = text_field_tag "title", nil, :class => 'field', :placeholder => "Type What You Need Done Here"
        %button{:type => "submit"} Plant

app/views/admin/projects/_recent_projects.haml
.rightside
  .boxheadin
    %h3 Recent Projects
  .recentprojects
    - @projects.each do |project|
      = link_to project.title, project_url(project.id)
      %p
        %b By:
        = link_to project.user.username, profile_url(project.user)
        %a#stay-target-1.stay-tooltip-target.tooltip-target
      #stay-content-1.stay-tooltip-username.tooltip-username
        %a{:href => "#"} Sample Name
        %p New York City, New York
        %ul
          %li.up 215
          %li.down 0
      %p.status
        %em Status:
        %i.completed
          = project.sm_state

app/views/admin/projects/create.js.haml
location.reload();

app/views/admin/projects/index.html.haml
- content_for :keywords, @tags
= render :partial => 'plant'
#container
  #main
    .content
      .head
        .left
          %h5 Pending Approval
        .right
          %ul.big
            %li= link_to('All', projects_url, :class => "active")
            %li= link_to 'Open', projects_url(:filter => 'open')
            %li= link_to 'Completed', projects_url(:filter => 'completed')
      #inboxhead
        %b.left Order #
        %b.right Updated
        .clear
      #inbox
        .post{:style=>'border-bottom: 1px solid #D6BF9E;'}
          - @projects.each do |project|
            .row
              .field
                = link_to project.id, project_inside_path(project.id)
              .field
                = project.title
              .field
                = project.updated_at.strftime("%b %d, %Y")
              .field
                = link_to 'approve', admin_project_approve_url(project.id)
            .clear
      .pagination{:style => 'float: left; margin-top: 20px; margin-left: 300px;'}
        = will_paginate @projects
  .clear

app/views/admin/projects/inside.html.haml
- content_for :keywords, @tags
= render :partial => 'plant'
#container
  #main
    .rightside
      .boxheadin
        %h3 Report a Problem
      .box
        = image_tag 'icon_report.png', :style => 'float: left;margin-right:10px;'
        = link_to 'Report a problem', new_project_problem_url(@project.id)
    .leftside
      .content
        .head
          .left
            %h5 Projects
          .right
            %ul.big
              %li= link_to('All', projects_url, :class => "active")
              %li= link_to 'Open', projects_url(:filter => 'open')
              %li= link_to 'Completed', projects_url(:filter => 'completed')
        #inboxhead
          %b.left Order #
          %b.right Updated
          .clear
        #inbox
          %ul
            = render :partial => 'messages', :locals => {:project => @project}
        #paginationholder
          .pagination
            %ol.wp-paginate
              %li
                %span.title
              %li
                %a.prev{:href => "#"} ‹‹
              %li
                %span.currentpage 1
              %li
                %a.page{:href => "#", :title => "2"} 2
              %li
                %a.page{:href => "#", :title => "3"} 3
              %li
                %a.page{:href => "#", :title => "4"} 4
              %li
                %a.next{:href => "#"} ››
  .clear

app/views/admin/projects/new.html.haml
= stylesheet_link_tag 'application'

:css
  a:active, a:focus, button{outline: 0;}
  .left, .right {text-align: left; padding: 20px 0 20px 20px}
  .right {padding:20px 20px 20px 0px}
  .left, .labelholder {float: left}
  .right, #plantseed i {float: right}
  .clear {clear: both}
  h2, h5 {font-family:'KnockoutHTF27-JuniorBantamwt', Hevletica, sans-serif; text-transform: uppercase; font-weight: normal}
  h3 {font-family: 'CoquetteBoldRegular', Georgia, Serif; font-weight: normal}

  #needdone h4 {
    color: #313104;
    font-size: 32px;
    text-shadow: 1px 1px 0 #BFC15A;
    margin-left: 20px;
  }

  #needdone {
      background: url("/images/ribbon-short.png") no-repeat scroll center center transparent;
      height: 110px;
      margin-left: -1px;
      margin-top: -30px;
  }

  #subhead {
      background-color: #E5D7C1;
      border-radius: 20px 20px 0 0;
      height: 52px;
      width: 583px;
  }
  #plantseed .right p i {float: none; margin-bottom: 20px; padding: 0}
  #plantseed .head {
  background-color: green;
  padding: 30px 30px 25px 30px;
  background: -webkit-gradient(
      linear,
      left bottom,
      left top,
      color-stop(0.19, rgb(122,124,30)),
      color-stop(0.58, rgb(159,161,36))
  );
  background: -moz-linear-gradient(
      center bottom,
      rgb(122,124,30) 19%,
      rgb(159,161,36) 58%
  );
  border-bottom: 1px solid #606117;
  border-bottom: 1px solid #606117;
  -moz-border-radius-topleft: 14px;
  -moz-border-radius-topright: 14px;
  -moz-border-radius-bottomright: 0px;
  -moz-border-radius-bottomleft: 0px;
  border-top-left-radius: 14px;
  border-top-right-radius: 14px;
  border-bottom-right-radius: 0px;
  border-bottom-left-radius: 0px;
  }

  h3 {font-family: 'CoquetteBoldRegular', Georgia, Serif; font-weight: normal}
  textarea {resize:none;}
  #plantseed {margin:0 auto;}
  #plantseed .left {width: 490px; }
  #plantseed .right {width: 190px }
  #plantseed .labelholder {width: 140px; text-align: right; padding: 4px 14px 0 0;}
  #plantseed label, h5, h5.due {color: #422215; font-size: 18px; font-weight: bold; }
  #plantseed i {font-style: normal; color: #894125; font-size: 11px}

  #plantseed input.field, input.price, input.year, textarea, input.city {
  padding: 12px;
  border: 1px solid #c3b288;
  font: 14px Georgia,'Times New Roman',Serif;
  font-style: italic;
  color: #3c3c39;
  width: 300px;
  margin-bottom: 14px;
  }

  input.city {
    width: 160px;
    padding: 6px;
  }

  #plantseed {
    margin-bottom: 40px;
    border-bottom-left-radius: 20px;
    border-bottom-right-radius: 20px;
    background-color: #E5D7C1;
    font: 12px Helvetica,Arial,Sans-Serif;
    height: 100%;
    width: 980px;
    text-align: center;
  }



  input.price {font: bold 16px Helvetica, Arial, Sans-Serif; font-style: normal; color: #585A05; width: 50px }
  input.year {font: bold 14px Helvetica, Arial, Sans-Serif; font-style: normal; padding: 10px; width: 150px; color: #422215}
  p {padding-bottom: 10px; margin: 0}
  select {float: left;  width: 179px; margin: 0px 0 10px 0}
  textarea {resize:none;}


  #plantseed textarea {
  font: 12px Helvetica,Arial,Sans-Serif;
  height: 100px;
  padding: 12px;
  }

  #plantseed h4 {margin-bottom: 0; margin-top: 10px; color: #422215;}
  #plantseed h5 {font-size: 18px; margin: 0; padding: 0}

  #plantseed a.plantseed, #plantseed .plantseed {
  background: url(../images/plantseed.png) no-repeat;
  border: none;
  height: 73px;
  text-indent: -9999em;
  display: block;
  margin: 0 auto;
  margin-top: -24px
  }


  #plantseed a.plantseed:hover, #plantseed .plantseed:hover {
  -webkit-box-shadow: 0px 0px 8px #000;
  -moz-box-shadow: 0px 0px 8px #000;
  box-shadow: 0px 0px 8px #000;
  -moz-border-radius: 22px;
  border-radius: 22px;
  }

  #plantseed .plantseed {
  width: 240px;
  margin: 0 370px 0;
  }

  select.month, select.day, select.year, #project_due_date_2i, #project_due_date_1i, #project_due_date_3i {width: 48px; float: left; margin-right: 8px}
  select.year, #project_due_date_1i {width: 60px}
#subhead
.holder
#needdone
  .holder
    %h4 Plant A Seed
.container
  #plantseed
    #new_project_form
      = render :partial => 'form', :locals => {:project => @project}

app/views/admin/projects/new.js.haml
$("#new_project_form").html('#{escape_javascript(render :partial => 'form', :locals => {:project => @project})}')

app/views/admin/projects/show.html.haml
= render :partial => 'plant'
#container
  #main
    .rightside
    .content
      .convohead
        .left
          %h5 Project Description
      #listings
        .posttwo{:style=>'background: inherit;'}
          .info
            %h2= @project.title
            %ul.posted
              %li
                %b Due:
                = @project.due_date.strftime("%m/%d/%Y")
              %li
                %b By:
                %a#stay-target-1.stay-tooltip-target.tooltip-target= link_to @project.user.profile.full_name, profile_path(@project.user)

            %ul.posted
              %li{:style => 'float: left;'}
                %b In Category:
                = link_to @project.category, root_url(:category => @project.category)
                .clear

              %li.sprowtit{:style => 'float: right;margin-right: -110px;'}
                = link_to(image_tag('button_sprowtit.png'), new_project_bid_path(:project_id => @project.id))
                .clear

              %li{:style => 'float: left; margin-top: 20px;'}
                - unless @project.city.blank? || @project.state.blank?
                  %b Location:
                  = link_to "#{@project.city}, #{@project.state}", '#'
                .clear
            .clear
            #description
            %p= @project.description
            %ul.actions
              %li
                = link_to "Create Similar", new_project_url(:source_id => @project.id)
              %li.share
                = display_sharing_tooltip
            #stay-content-2.stay-tooltip-username.tooltip-share
              %ul
                %li
                  %a.facebook{:href => "#"}
                %li
                  %a.twitter{:href => "#"}
                %li
                  %a.email{:href => "#"}
          .price
            %h4= number_to_currency(@project.price, :precision => 0)
            %i Asking Price
          .clear
  .clear